### PR TITLE
Optimized implementation of JSON-LD serialization

### PR DESCRIPTION
**Pull request by likelion**
I did some profiling and got the following performance while serializing into JSON-LD http://localhost:3020/oslc_shapes.

```
% 105,385 inferences, 0.016 CPU in 0.017 seconds (96% CPU, 6443595 Lips)
```

### CODE REVIEW

**Comment by morlic** [comment]
what at did you time?

**Comment by likelion** [comment]
I wrapped the body of `	oslc_dispatch:serialize_response` in `time()`. Then `curl -H “Accept:application/ld+json” http://localhost:3020/oslc_shapes`. The number of inferences is the most important.

**Comment by morlic** [comment]
Objects IRIs that occur as objects are not correctly encoded with {@id:...} (except in @type which should be a special case):

rdf(oslc_shapes:allowedValuesShape, oslc:describes, oslc:AllowedValues).

GET /oslc_shapes/allowedValuesShape

```
[
    {
        "@context": {
            "dcterms": "http://purl.org/dc/terms/",
            "oslc": "http://open-services.net/ns/core#",
            "oslc_shapes": "http://ontology.cf.ericsson.net/oslc_shapes/"
        },
        "@id": "oslc_shapes:allowedValuesShape",
        "@type": "oslc:ResourceShape",
        "dcterms:description": "Allowed values for one property.",
==>     "oslc:describes": "oslc:AllowedValues",
        "oslc:property": {
            "@type": "oslc:Property",
            "dcterms:description": "Value allowed for a property.",
            "oslc:name": "allowedValue",
==>         "oslc:occurs": "oslc:One-or-many",
==>         "oslc:propertyDefinition": "oslc:allowedValue",
            "oslc:readOnly": "true"
        }
    }
]
```
the result should be:
```
[
    {
        "@context": {
            "dcterms":"http://purl.org/dc/terms/",
            "oslc":"http://open-services.net/ns/core#",
            "oslc_shapes": "http://ontology.cf.ericsson.net/oslc_shapes/"
        },
        "@id":"oslc_shapes:allowedValuesShape",
        "@type":"oslc:ResourceShape",
        "dcterms:description":"Allowed values for one property.",
==>     "oslc:describes": {"@id":"oslc:AllowedValues"},
        "oslc:property": {
            "@type":"oslc:Property",
            "dcterms:description":"Value allowed for a property.",
            "oslc:name":"allowedValue",
==>         "oslc:occurs": {"@id":"oslc:One-or-many"},
==>         "oslc:propertyDefinition": {"@id":"oslc:allowedValue"},
            "oslc:readOnly":"true"
        }
    }
]
```

**Comment by likelion** [comment]
@morlic Anything else to fix, or shall we merge?

**Comment by likelion** [comment]
@likelion thanx for the bug!

**Comment by morlic** [comment]
Good to go!

**Review by morlic — APPROVED** [review]

**Pull request merged**
